### PR TITLE
Update test.tf

### PR DESCRIPTION
**Pull request by ludoo-test**

### CODE REVIEW

**Comment by ludoo** [comment]
**Plan Error**
```
atlantis.yaml files not allowed because Atlantis is not running with --allow-repo-config
```

**Comment by ludoo-test** [comment]
atlantis plan

**Comment by ludoo** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.test-1
      id: <computed>

+ null_resource.test-2
      id: <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3778a1e5.ngrok.io/lock?id=ludoo%252Fatlantis_test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ludoo-test** [comment]
atlantis apply

**Comment by ludoo** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be mergeable before running apply.

**Comment by ludoo-test** [comment]
atlantis plan -d

**Comment by ludoo** [comment]
```
Error: flag needs an argument: 'd' in -d.
Usage of plan:
  -d, --dir string         Which directory to run plan in relative to root of repo,
                           ex. 'child/dir'.
  -p, --project string     Which project to run plan for. Refers to the name of the
                           project configured in atlantis.yaml. Cannot be used at
                           same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Switch to this Terraform workspace before planning.
```

**Comment by ludoo-test** [comment]
atlantis plan -d .

**Comment by ludoo** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.test-1
      id: <computed>

+ null_resource.test-2
      id: <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3778a1e5.ngrok.io/lock?id=ludoo%252Fatlantis_test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ludoo-test** [comment]
atlantis apply .

**Comment by ludoo** [comment]
```
Error: unknown argument(s) – ..
Usage of apply:
  -d, --dir string         Apply the plan for this directory, relative to root of
                           repo, ex. 'child/dir'.
  -p, --project string     Apply the plan for this project. Refers to the name of
                           the project configured in atlantis.yaml. Cannot be used
                           at same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Apply the plan for this Terraform workspace.
```

**Comment by ludoo-test** [comment]
atlantis apply

**Comment by ludoo** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
null_resource.test-2: Creating...
null_resource.test-1: Creating...
null_resource.test-2: Creation complete after 0s (ID: 1317365680289615086)
null_resource.test-1: Creation complete after 0s (ID: 231590048029393515)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```

**Comment by ludoo** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
