### PR TITLE
Create test.tf with single null resource

### PR DESCRIPTION
**Pull request by ludoo-test**

### CODE REVIEW

**Comment by ludoo** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.test-1
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3778a1e5.ngrok.io/lock?id=ludoo%252Fatlantis_test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ludoo-test** [comment]
atlantis apply -d .

**Comment by ludoo** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
null_resource.test-1: Creating...
null_resource.test-1: Creation complete after 0s (ID: 7902711533690380805)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by ludoo** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
